// <auto-generated />
namespace Voting_System.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addnumberofvotestodetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addnumberofvotestodetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202101242125111_addnumberofvotestodetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
